//! # Create Quote DTO
//!
//! Defines the **request body shape** for the `POST /quotes` endpoint.
//!
//! These structs represent what the API consumer sends when creating a new quote.
//! They are deserialized from JSON by Axum's `Json<T>` extractor before the handler
//! is called. If a required field is missing or has the wrong type, Axum automatically
//! returns `422 Unprocessable Entity` without reaching the handler.
//!
//! ## What is intentionally absent
//! - `id` — auto-generated by the database.
//! - `total` — computed by the repository from the detail lines; clients must not
//!   send it to prevent manipulation.
//!
//! ## Naming convention
//! `#[serde(rename_all = "camelCase")]` is applied so that JSON keys follow
//! JavaScript/TypeScript conventions (e.g. `clientId`, `statusId`, `createdAt`,
//! `unitCost`) while Rust fields use `snake_case` internally.

use serde::Deserialize;
use chrono::NaiveDate;
use rust_decimal::Decimal;


/// Payload received by `POST /quotes`.
///
/// Carries all the information needed to create a quote header plus its line items.
/// The `details` array must contain **at least one item** — this invariant is
/// enforced in the service layer (`service::create_quote`) before the repository
/// is called, and also defensively checked in the repository itself.
///
/// # Example JSON
/// ```json
/// {
///   "clientId": 5,
///   "statusId": 1,
///   "createdAt": "2025-04-10",
///   "details": [
///     {
///       "productId": 12,
///       "unitCost": "150.00",
///       "tax": "10",
///       "quantity": 3
///     }
///   ]
/// }
/// ```
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateQuoteDto {
    /// Foreign key referencing the client this quote is issued for (`clients.id`).
    pub client_id: i32,
 
    /// Foreign key referencing the initial workflow status (`statuses.id`).
    /// Typically the ID for "Draft" on creation.
    pub status_id: i32,
 
    /// Issue date of the quote. Serialized as `"YYYY-MM-DD"` in JSON.
    /// Uses [`NaiveDate`] because no timezone information is needed for
    /// a business document date.
    pub created_at: NaiveDate,
 
    /// One or more line items to attach to this quote.
    /// Must not be empty — enforced before any database writes occur.
    pub details: Vec<CreateQuoteDetailDto>,
}


/// A single line item within the create quote payload.
///
/// Each entry results in one INSERT into `quote_details`.
/// The repository computes `subtotal` from these values and accumulates
/// them into the quote's `total` — neither field needs to be sent by the client.
///
/// ## Subtotal formula (computed server-side)
/// `subtotal = unit_cost * quantity + (unit_cost * quantity * tax / 100)`
///
/// # Example JSON
/// ```json
/// {
///   "productId": 7,
///   "unitCost": "200.00",
///   "tax": "15",
///   "quantity": 2
/// }
/// ```

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateQuoteDetailDto {
    /// Foreign key referencing the product for this line (`products.id`).
    pub product_id: i32,
 
    /// Price per unit. Sent as a decimal string in JSON to preserve precision.
    /// Stored as `NUMERIC` in the database.
    pub unit_cost: Decimal,
 
    /// Tax percentage for this line (e.g. `10` means 10%).
    /// Stored as `NUMERIC` in the database.
    pub tax: Decimal,
 
    /// Number of units. Must be a positive integer.
    pub quantity: i32,
}
