//! # Create Client DTO
//!
//! Defines the request body shape for the `POST /clients` endpoint.
//!
//! These structs represent **what the API consumer sends** when creating a new client.
//! They intentionally omit fields that are either auto-generated by the database (`id`)
//! or managed by business logic (`current_credit`, which always starts at 0).
//!
//! `#[serde(rename_all = "camelCase")]` is applied so that JSON keys follow
//! JavaScript/TypeScript naming conventions (e.g. `birthDate`, `creditLimit`, `isEmergency`)
//! while Rust fields follow snake_case internally.

use chrono::NaiveDate;
use serde::{Deserialize, Serialize};

/// Payload received by `POST /clients`.
///
/// All fields are validated implicitly by serde — if a required field is missing
/// or of the wrong type, Axum will return a `422 Unprocessable Entity` before
/// the handler is even called.
///
/// # Required fields
/// `name`, `surname`, `document`, `email`, `phones`
///
/// # Optional fields
/// `address`, `birth_date`, `credit_limit`
/// (if `credit_limit` is omitted it defaults to `0.0` in the repository)
///
/// # Example JSON
/// ```json
/// {
///   "name": "John",
///   "surname": "Doe",
///   "document": "1234567",
///   "email": "john@example.com",
///   "birthDate": "1990-05-20",
///   "creditLimit": 5000.00,
///   "phones": [
///     { "phoneNumber": "0981123456", "isEmergency": false }
///   ]
/// }
/// ```

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]  //birthDate, creditLimit, etc
pub struct CreateClientDto {
    /// Client's first name. Maps to the `name` column in `clients`.
    pub name: String,
    
    /// Client's last name. Maps to the `surname` column in `clients`.
    pub surname: String,
    
    /// National ID or document number. Maps to the `document` column in `clients`.
    pub document: String,
    
    /// Optional mailing address. Maps to the `address` column in `clients`.
    pub address:Option< String>,
    
    /// Contact email address. Maps to the `email` column in `clients`.    
    pub email: String,
    
    /// Date of birth. Serialized as `"YYYY-MM-DD"` in JSON.
    /// Maps to the `birth_date` column (`DATE` type) in `clients`.
    pub birth_date: Option<NaiveDate>,
    
    /// Maximum credit the client is allowed. Defaults to `0.0` if omitted.
    /// Maps to the `credit_limit` column in `clients`.
    pub credit_limit: Option<f64>,
    
    /// List of phone numbers to associate with this client.
    /// Can be an empty array `[]` if no phones are provided yet.
    /// Each phone is inserted into `phone_numbers` and linked via `clients_phones`.
    pub phones: Vec<CreatePhoneDto>,
}


/// Represents a single phone number to be created alongside a new client.
///
/// Used as a nested object inside [`CreateClientDto`].
/// Each entry results in one INSERT into `phone_numbers` and one INSERT
/// into the `clients_phones` pivot table.
///
/// # Example JSON
/// ```json
/// { "phoneNumber": "0981123456", "isEmergency": true }
/// ```

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreatePhoneDto {
    /// The phone number string. No format is enforced here;
    /// format validation should be added in the service layer if needed.    
    pub phone_number: String,

    /// Whether this is the client's emergency contact number.
    /// Maps to the `is_emergency` column in `phone_numbers`.    
    pub is_emergency: bool,
}
