//! # Purchase Payment Order Domain Models
//!
//! This module defines the **internal data structures** that represent the
//! purchase payment order domain.
//!
//! These structs mirror the database schema and the JOIN projections used by
//! the repository layer, but they are **not serialized directly** into API
//! responses. Instead, they should be converted into response DTOs through the
//! mapper layer.
//!
//! ## Database tables involved
//! - `purchase_payment_orders`         → [`PurchasePaymentOrder`]
//! - `purchase_payment_order_details`  → [`PurchasePaymentOrderDetail`]
//! - `suppliers`                       → [`PurchasePaymentOrderSupplier`]
//! - `statuses`                        → [`PurchasePaymentOrderStatus`]
//! - `employees`                       → [`PurchasePaymentOrderEmployee`]
//! - `purchase_invoices`               → [`PurchasePaymentOrderInvoice`]
//!
//! ## Aggregate pattern
//! [`PurchasePaymentOrderWithDetails`] is the root aggregate of this domain.
//! It is the structure returned by repository read operations and later mapped
//! into [`crate::modules::purchase_payment_order::dto::response::PurchasePaymentOrderResponseDto`].

use chrono::NaiveDate;
use rust_decimal::Decimal;

/// The main purchase payment order entity.
///
/// Corresponds to a single row in the `purchase_payment_orders` table.
///
/// A purchase payment order represents a request for treasury to pay one or more
/// supplier invoices. The actual invoices included in the order are stored in
/// [`PurchasePaymentOrderDetail`].
#[derive(Debug, Clone)]
pub struct PurchasePaymentOrder {
    /// Primary key — auto-generated by the database.
    pub id: i32,

    /// Creation date of the payment order.
    ///
    /// In the database this defaults to `CURRENT_DATE`.
    pub created_at: NaiveDate,

    /// Foreign key referencing `suppliers.id`.
    ///
    /// The resolved supplier snapshot is stored in
    /// [`PurchasePaymentOrderWithDetails::supplier`].
    pub supplier_id: i32,

    /// Foreign key referencing `statuses.id`.
    ///
    /// The resolved status snapshot is stored in
    /// [`PurchasePaymentOrderWithDetails::status`].
    pub status_id: i32,

    /// Optional foreign key referencing the employee who requested the payment order.
    ///
    /// Nullable because the table allows `requested_by_employee_id` to be `NULL`.
    pub requested_by_employee_id: Option<i32>,

    /// Optional foreign key referencing the employee who approved the payment order.
    ///
    /// Usually `None` while the order is still pending.
    pub approved_by_employee_id: Option<i32>,

    /// Planned payment date.
    ///
    /// This is only a scheduling/reference date. The real payment date should
    /// belong to the actual payment table, if you later add one.
    pub scheduled_payment_date: Option<NaiveDate>,

    /// Header-level notes for treasury.
    pub observations: Option<String>,
}

/// A lightweight supplier projection used inside the payment order aggregate.
///
/// Populated through a `JOIN suppliers` in the repository.
/// Only includes the fields needed to display the supplier in this context.
#[derive(Debug, Clone)]
pub struct PurchasePaymentOrderSupplier {
    /// Primary key of the supplier.
    pub id: i32,

    /// Supplier display name.
    ///
    /// If your `suppliers` table uses another field such as `business_name`
    /// or `company_name`, adjust both this model and the repository alias.
    pub name: String,
}

/// A lightweight workflow status projection.
///
/// Populated through a `JOIN statuses` in the repository.
#[derive(Debug, Clone)]
pub struct PurchasePaymentOrderStatus {
    /// Primary key of the status.
    pub id: i32,

    /// Human-readable status label.
    ///
    /// Examples: `"Pending"`, `"Approved"`, `"Paid"`, `"Cancelled"`.
    pub status: String,
}

/// A lightweight employee projection used for requester and approver.
///
/// Populated through `LEFT JOIN employees` because both requester and approver
/// are nullable in the payment order table.
#[derive(Debug, Clone)]
pub struct PurchasePaymentOrderEmployee {
    /// Primary key of the employee.
    pub id: i32,

    /// Employee first name.
    pub name: String,

    /// Employee surname.
    pub surname: String,
}

/// A lightweight purchase invoice projection used inside payment order details.
///
/// Populated through a `JOIN purchase_invoices`.
///
/// This model includes both stored invoice values and the derived
/// `pending_amount`, which is computed as:
///
/// `pending_amount = total - total_paid`
#[derive(Debug, Clone)]
pub struct PurchasePaymentOrderInvoice {
    /// Primary key of the purchase invoice.
    pub id: i32,

    /// Invoice number.
    pub invoice_nr: String,

    /// Foreign key referencing `purchase_orders.id`.
    pub purchase_order_id: i32,

    /// Invoice creation date.
    pub created_at: NaiveDate,

    /// Original invoice total.
    ///
    /// Stored as `NUMERIC`/`DECIMAL` in PostgreSQL and represented as
    /// [`Decimal`] to avoid floating-point precision errors.
    pub total: Decimal,

    /// Amount already paid for this invoice.
    pub total_paid: Decimal,

    /// Remaining balance of the invoice.
    ///
    /// Computed in the repository query as `pi.total - pi.total_paid`.
    pub pending_amount: Decimal,
}

/// A single invoice line within a purchase payment order.
///
/// Corresponds to a row in `purchase_payment_order_details`.
///
/// Each detail links a payment order to a purchase invoice and specifies how
/// much should be paid for that invoice.
#[derive(Debug, Clone)]
pub struct PurchasePaymentOrderDetail {
    /// Primary key of this detail row.
    pub id: i32,

    /// Foreign key back to the parent payment order.
    pub purchase_payment_order_id: i32,

    /// Snapshot of the invoice being paid.
    pub purchase_invoice: PurchasePaymentOrderInvoice,

    /// Amount requested to pay for this invoice.
    ///
    /// Allows partial payments. The database enforces `amount_to_pay > 0`.
    /// The service layer should also validate that this amount does not exceed
    /// the invoice pending balance.
    pub amount_to_pay: Decimal,

    /// Optional line-level notes.
    pub observations: Option<String>,
}

/// The fully hydrated root aggregate for a purchase payment order.
///
/// This combines:
/// - the payment order header,
/// - supplier,
/// - status,
/// - requester,
/// - approver,
/// - calculated total to pay,
/// - and all invoice details.
///
/// It is returned by repository read operations and should be converted into
/// a response DTO by the mapper layer.
#[derive(Debug, Clone)]
pub struct PurchasePaymentOrderWithDetails {
    /// Scalar payment order data.
    pub payment_order: PurchasePaymentOrder,

    /// Snapshot of the supplier associated with this order.
    pub supplier: PurchasePaymentOrderSupplier,

    /// Current workflow status of the payment order.
    pub status: PurchasePaymentOrderStatus,

    /// Employee who requested the payment order.
    ///
    /// `None` when `requested_by_employee_id` is `NULL`.
    pub requested_by_employee: Option<PurchasePaymentOrderEmployee>,

    /// Employee who approved the payment order.
    ///
    /// `None` while the order is not yet approved.
    pub approved_by_employee: Option<PurchasePaymentOrderEmployee>,

    /// Sum of all detail `amount_to_pay` values.
    ///
    /// This value is computed while assembling the aggregate in the repository.
    /// It is not stored in the database.
    pub total_to_pay: Decimal,

    /// Invoices included in this payment order.
    pub details: Vec<PurchasePaymentOrderDetail>,
}