//! # Quote Domain Models
//!
//! This module defines the **internal data structures** that represent the quote domain.
//! These structs mirror the database schema but are **never serialized directly** into
//! API responses. Instead, they are transformed into response DTOs via the mapper layer
//! (`mapper.rs`), keeping the public API contract decoupled from the storage schema.
//!
//! ## Database tables involved
//! - `quotes`        → [`Quote`]
//! - `clients`       → [`QuoteClient`]  (read-only projection / snapshot)
//! - `statuses`      → [`QuoteStatus`]  (read-only projection / snapshot)
//! - `quote_details` → [`QuoteDetail`]
//! - `products`      → [`QuoteProduct`] (read-only projection / snapshot)
//!
//! ## Why "snapshot" structs?
//! [`QuoteClient`], [`QuoteStatus`], and [`QuoteProduct`] are **lightweight projections**
//! of their respective tables, containing only the fields needed to render a quote.
//! They are populated via JOINs in the repository and intentionally do not import or
//! reuse the full entity types from other modules. This keeps the quote aggregate
//! self-contained and avoids tight coupling between modules.
//!
//! ## Aggregate pattern
//! [`QuoteWithDetails`] is the root aggregate of this domain. It is the single
//! structure returned by every repository read operation and passed up through the
//! service and mapper layers before being converted into a
//! [`crate::modules::quote::dto::response::QuoteResponseDto`].

use chrono::NaiveDate;
use rust_decimal::Decimal;


/// The main quote entity. Corresponds to a single row in the `quotes` table.
///
/// `total` is stored as `NUMERIC` in PostgreSQL and represented here as [`Decimal`]
/// (from the `rust_decimal` crate) to avoid floating-point precision errors in
/// financial calculations.
///
/// `client_id` and `status_id` are foreign keys — the actual related data is resolved
/// via JOINs and stored in [`QuoteWithDetails`] as [`QuoteClient`] and [`QuoteStatus`].

#[derive(Debug, Clone)]
pub struct Quote {
    /// Primary key — auto-generated by the database.    
    pub id: i32,

    /// The date the quote was issued. Uses [`NaiveDate`] (date only, no timezone)
    /// because business documents typically only need a calendar date, not a timestamp.
    pub created_at: NaiveDate,

    /// Computed total of all line items (sum of each detail's subtotal).
    /// Stored as `NUMERIC` in PostgreSQL. Initially inserted as `0` and updated
    /// after all details are inserted during the create transaction.
    pub total: Decimal,

    /// Foreign key referencing `clients.id`.
    /// The resolved client snapshot is in [`QuoteWithDetails::client`].
    pub client_id: i32,

    /// Foreign key referencing `statuses.id`.
    /// The resolved status snapshot is in [`QuoteWithDetails::status`].
    pub status_id: i32,
}


/// A lightweight snapshot of the client associated with a quote.
///
/// Populated via a `JOIN clients` in the repository's base query.
/// Only includes the fields needed to identify the client on a quote.
/// For full client data, refer to the `client` module.
#[derive(Debug, Clone)]
pub struct QuoteClient {
    /// Primary key of the client (`clients.id`).
    pub id: i32,
    pub name: String,
    pub surname: String,

    /// National ID or document number — used as a business identifier.
    pub document: String,
}


/// A lightweight snapshot of the quote's current workflow status.
///
/// Populated via a `JOIN statuses` in the repository's base query.
/// Typical values: "Draft", "Sent", "Approved", "Rejected".
#[derive(Debug, Clone)]
pub struct QuoteStatus {
    /// Primary key of the status (`statuses.id`).
    pub id: i32,
    
    /// Human-readable label (e.g. `"Draft"`, `"Approved"`).
    pub status: String,
}

/// A lightweight snapshot of the product referenced in a quote line item.
///
/// Populated via a `LEFT JOIN products` in the repository's base query.
/// Only the fields needed to describe a product in a quote context are included.
#[derive(Debug, Clone)]
pub struct QuoteProduct {
    /// Primary key of the product (`products.id`).
    pub id: i32,

    /// Full product description shown on the quote document.
    pub description: String,
    
    /// Product SKU or short identification code.
    pub code: String,
}


/// A single line item within a quote. Corresponds to a row in `quote_details`.
///
/// Each detail links a quote to a product with a specific quantity, unit cost,
/// and tax rate. The `subtotal` is **computed at read time** in the repository
/// and is NOT stored in the database — it is derived on every fetch to ensure
/// consistency with the stored `unit_cost`, `tax`, and `quantity` values.
///
/// ## Subtotal formula
/// `subtotal = unit_cost * quantity + (unit_cost * quantity * tax / 100)`
#[derive(Debug, Clone)]
pub struct QuoteDetail {
    /// Primary key of this detail row (`quote_details.id`).
    pub id: i32,

    /// Foreign key back to the parent quote (`quote_details.quote_id`).
    /// Redundant when accessed through [`QuoteWithDetails`], but kept for
    /// standalone processing scenarios.
    pub quote_id: i32,
    
    /// Snapshot of the associated product, resolved via LEFT JOIN.
    pub product: QuoteProduct,
    
    /// Price per unit at the time the quote was created.
    /// Stored as `NUMERIC` in the DB — [`Decimal`] preserves full precision.
    pub unit_cost: Decimal,
    
    /// Tax percentage for this line item (e.g. `10` = 10%).
    /// Stored as `NUMERIC` in the DB.
    pub tax: Decimal,
    
    /// Number of units of this product included in the quote.
    pub quantity: i32,
    
    /// Derived subtotal for this line item. Computed in the repository during
    /// aggregate assembly. Not persisted in the database.
    pub subtotal: Decimal,
}


/// The fully hydrated root aggregate for a quote.
///
/// This is the central data structure of the quote domain. It combines the scalar
/// quote data with all its resolved relationships (client, status, line items)
/// into a single in-memory object ready for the service and mapper layers.
///
/// ## How it is built
/// The repository executes a single SQL query with multiple JOINs, producing
/// one row per detail line. The private `rows_to_aggregate` function collapses
/// those rows using a `BTreeMap<quote_id, QuoteWithDetails>`, appending each
/// detail to the matching quote entry.
///
/// ## How it is consumed
/// Returned from the repository → passed to
/// [`crate::modules::quote::mapper::quote_with_details_to_response`] →
/// converted into [`crate::modules::quote::dto::response::QuoteResponseDto`]
/// for HTTP serialization.

#[derive(Debug, Clone)]
pub struct QuoteWithDetails {
    /// Scalar quote data (id, date, total, foreign keys).
    pub quote: Quote,
    
    /// Snapshot of the client associated with this quote.
    pub client: QuoteClient,
    
    /// Snapshot of the current status of this quote.
    pub status: QuoteStatus,
    
    /// All line items belonging to this quote.
    /// Will be an empty `Vec` for list-only queries that skip the details JOIN.
    pub details: Vec<QuoteDetail>,
}
