//! # Create Purchase Payment Order DTO
//!
//! Defines the **request body shape** for the `POST /purchase-payment-orders` endpoint.
//!
//! These structs represent what the API consumer sends when creating a new payment
//! order for supplier invoices.
//!
//! ## What is intentionally absent
//! - `id` — auto-generated by the database.
//! - `created_at` — generated by the database with `CURRENT_DATE`.
//! - `approved_by_employee_id` — should be assigned later when the order is approved.
//! - `total` — computed from the detail lines; clients must not send it.
//!
//! ## Naming convention
//! `#[serde(rename_all = "camelCase")]` is applied so that JSON keys follow
//! JavaScript/TypeScript conventions while Rust fields use `snake_case`.

use serde::Deserialize;
use chrono::NaiveDate;
use rust_decimal::Decimal;

/// Payload received by `POST /purchase-payment-orders`.
///
/// Carries all the information needed to create a payment order header plus
/// the invoices that should be paid.
///
/// The `details` array must contain **at least one item**. This should be
/// validated in the service layer before calling the repository.
///
/// # Example JSON
/// ```json
/// {
///   "supplierId": 3,
///   "statusId": 1,
///   "requestedByEmployeeId": 8,
///   "scheduledPaymentDate": "2026-05-15",
///   "observations": "Pagar facturas vencidas del proveedor.",
///   "details": [
///     {
///       "purchaseInvoiceId": 12,
///       "amountToPay": "1500000.00",
///       "observations": "Pago parcial"
///     },
///     {
///       "purchaseInvoiceId": 13,
///       "amountToPay": "800000.00"
///     }
///   ]
/// }
/// ```
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreatePurchasePaymentOrderDto {
    /// Foreign key referencing the supplier to be paid (`suppliers.id`).
    ///
    /// Every invoice included in `details` must belong to this same supplier.
    /// This invariant should be validated in the service/repository layer.
    pub supplier_id: i32,

    /// Foreign key referencing the initial workflow status (`statuses.id`).
    ///
    /// Usually this would be the ID for something like `"Pending"`,
    /// `"Draft"` or `"Requested"`.
    pub status_id: i32,

    /// Employee who requested/created the payment order.
    ///
    /// If your API has authentication, this could also be taken from the
    /// authenticated user instead of the request body.
    pub requested_by_employee_id: Option<i32>,

    /// Planned payment date. Serialized as `"YYYY-MM-DD"` in JSON.
    pub scheduled_payment_date: Option<NaiveDate>,

    /// Optional header-level notes for treasury.
    pub observations: Option<String>,

    /// One or more invoices to include in the payment order.
    ///
    /// Must not be empty.
    pub details: Vec<CreatePurchasePaymentOrderDetailDto>,
}

/// A single invoice line within the create payment order payload.
///
/// Each entry results in one INSERT into `purchase_payment_order_details`.
///
/// # Example JSON
/// ```json
/// {
///   "purchaseInvoiceId": 12,
///   "amountToPay": "1500000.00",
///   "observations": "Pago parcial"
/// }
/// ```
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CreatePurchasePaymentOrderDetailDto {
    /// Foreign key referencing the invoice to pay (`purchase_invoices.id`).
    pub purchase_invoice_id: i32,

    /// Amount to pay for this invoice.
    ///
    /// Allows partial payments. Must be greater than zero and should not exceed
    /// the invoice pending balance: `total - total_paid`.
    pub amount_to_pay: Decimal,

    /// Optional line-level note.
    pub observations: Option<String>,
}