//! # Client Domain Models
//!
//! This module defines the **internal data structures** that mirror the database schema.
//! These types are used exclusively within the application layer — they are never
//! serialized directly to API responses. Instead, they are mapped into DTOs (see `dto/response.rs`)
//! before being returned to the caller.
//!
//! ## Database Schema Overview
//! - `clients`         → maps to [`Client`]
//! - `phone_numbers`   → maps to [`Phone`]
//! - `clients_phones`  → pivot/join table linking clients to their phones (many-to-many)

use chrono::NaiveDate;
use serde::{Deserialize, Serialize};

/// Represents a single row from the `clients` table.
///
/// This is the core entity of the module. It holds all scalar fields
/// belonging to a client. Phone numbers are **not** included here because
/// a client may have zero or more phones stored in a separate table (`phone_numbers`),
/// linked through the pivot table `clients_phones`.
///
/// `credit_limit` and `current_credit` are stored as `NUMERIC` in PostgreSQL
/// and explicitly cast to `float8` in every query to avoid type mismatch errors
/// when reading through `tokio_postgres`.

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Client{
    /// Primary key - auto-generated by the database.
    pub id: i32,

    /// Client's first name. Requiredm non-nullable in the DB.
    pub name: String,

    /// Client's last name. Required, non-nullable in the DB.
    pub surname: String,

    /// National ID or document number. Used as a unique business identifier.
    /// Required, non-nullable in the DB.
    pub document: String,

    /// Mailing or physical address. Optional — the client may not provide one.
    pub address: Option<String>,

    /// Contact email address. Required, non-nullable in the DB.
    pub email: String,
    
    /// Client's date of birth. Optional — stored as `DATE` in PostgreSQL,
    /// deserialized as `NaiveDate` (no timezone component needed).
    pub birth_date: Option<NaiveDate>,
    
    /// Maximum credit amount the client is allowed to use.
    /// Stored as `NUMERIC` in the DB; cast to `float8` in queries.
    pub credit_limit: f64,
    
    /// Credit already used by the client.
    /// Stored as `NUMERIC` (column name `curr_credit`) in the DB;
    /// cast to `float8` in queries. Note the column alias used in SQL.
    pub current_credit: f64,
}


/// Represents a single row from the `phone_numbers` table.
///
/// Phones are stored in a dedicated table because a single client can
/// have multiple phone numbers (one-to-many from client's perspective,
/// many-to-many at the schema level via `clients_phones`).
///
/// The `is_emergency` flag allows front-ends and staff to quickly identify
/// which number should be called in urgent situations.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Phone {
    /// Primary key — auto-generated by the database.
    pub id: i32,

    /// The actual phone number string (e.g. "+595 981 123 456").
    /// No format is enforced at the DB level; validation belongs in the service layer.
    pub phone_number: String,
    
    /// Whether this phone number is designated as an emergency contact.
    /// Stored as `BOOLEAN` in PostgreSQL.
    pub is_emergency: bool,
}


/// Aggregated view of a client together with all their associated phone numbers.
///
/// This struct is **not** a database table — it is an in-memory composition
/// assembled by [`crate::modules::client::repository::rows_to_aggregates`] after
/// executing a LEFT JOIN query.
///
/// ## Why an aggregate instead of nested queries?
/// A single LEFT JOIN query retrieves the client and all their phones in one
/// round-trip to the database. The trade-off is that the result set contains
/// duplicate client columns (one row per phone), which `rows_to_aggregates`
/// collapses using a `BTreeMap<client_id, ClientAggregate>`.
///
/// The aggregate is then converted to [`crate::modules::client::dto::response::ClientResponseDto`]
/// before being sent to the HTTP layer, keeping internal models decoupled from
/// the public API contract.
pub struct ClientAggregate {
    /// The scalar client data.
    pub client: Client,

    /// All phone numbers associated with this client.
    /// Will be an empty `Vec` if the client has no phones registered.
    pub phones: Vec<Phone>,
}
